### ISSUE TITLE
Tokenizer creation fails

### ISSUE THREAD

**Issue by sd00130** [ahomansikka/sukija#4]
When dataimporting got the folowing: 

solr version: 5.2.1

Exception in thread "Thread-21" java.lang.AbstractMethodError
        at org.apache.lucene.analysis.util.TokenizerFactory.create(TokenizerFactory.java:75)
        at org.apache.solr.analysis.TokenizerChain.createComponents(TokenizerChain.java:64)
        at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
        at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:179)
        at org.apache.lucene.document.Field.tokenStream(Field.java:564)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:606)
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:458)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1363)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:163)
        at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:955)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1110)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:706)
        at org.apache.solr.update.processor.LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:104)
        at org.apache.solr.handler.dataimport.SolrWriter.upload(SolrWriter.java:71)
        at org.apache.solr.handler.dataimport.DataImportHandler$1.upload(DataImportHandler.java:259)
        at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:524)
        at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:414)
        at org.apache.solr.handler.dataimport.DocBuilder.doFullDump(DocBuilder.java:329)
        at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:232)
        at org.apache.solr.handler.dataimport.DataImporter.doFullImport(DataImporter.java:416)
        at org.apache.solr.handler.dataimport.DataImporter.runCmd(DataImporter.java:480)
        at org.apache.solr.handler.dataimport.DataImporter$1.run(DataImporter.java:461)

My config is:

   <field name="finname" type="text_fi" indexed="true" stored="true"/>
   ....
   .... 
   ....
   ....
    
    <fieldType name="text_fi" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <charFilter class="solr.HTMLStripCharFilterFactory"/>
        <tokenizer class="peltomaa.sukija.finnish.FinnishTokenizerFactory"/>
        <filter class="peltomaa.sukija.malaga.MalagaMorphologyFilterFactory"
          malagaProjectFile="${solr.solr.home}/malaga/suomi.pro" 
          suggestionFile="${solr.solr.home}/malaga/suggestion.txt" 
          success="false"/>
        <filter class="solr.SynonymFilterFactory"
                synonyms="${solr.solr.home}/malaga/synonyms.txt" 
                ignoreCase="true"
                expand="false"/>
        <filter class="peltomaa.sukija.finnish.FinnishFoldingLowerCaseFilterFactory"/>
        <filter class="solr.HyphenatedWordsFilterFactory"/>
      </analyzer>
      <analyzer type="query">
          <charFilter class="solr.HTMLStripCharFilterFactory"/>
        <tokenizer class="solr.WhitespaceTokenizerFactory"/>
        <filter class="peltomaa.sukija.malaga.MalagaMorphologyFilterFactory" 
                malagaProjectFile="${solr.solr.home}/malaga/suomi.pro" 
            suggestionFile="${solr.solr.home}/malaga/suggestion.txt" 
            success="false"/>
        <filter class="peltomaa.sukija.finnish.FinnishFoldingLowerCaseFilterFactory"/>
      </analyzer>
    </fieldType>

What is the best way to resolve it?

**Comment by ahomansikka** [comment]
Undocumented feature: only variable that can be in sukija.properties is
${user.home}.

**Comment by ahomansikka** [comment]
Since everything seems to be ok, I close this issue.
